import type {
  ContactPayload,
  EventDirtyPayload,
  EventDongPayload,
  EventErrorPayload,
  EventFriendshipPayload,
  EventHeartbeatPayload,
  EventLoginPayload,
  EventLogoutPayload,
  EventMessagePayload,
  EventReadyPayload,
  EventResetPayload,
  EventRoomInvitePayload,
  EventRoomJoinPayload,
  EventRoomLeavePayload,
  EventRoomTopicPayload,
  EventScanPayload,
  FriendshipPayload,
  FriendshipPayloadConfirm,
  FriendshipPayloadReceive,
  FriendshipPayloadVerify,
  LocationPayload,
  MessagePayload,
  MessagePayloadBase,
  MessagePayloadRoom,
  MessagePayloadTo,
  MiniProgramPayload,
  RoomInvitationPayload,
  RoomMemberPayload,
  RoomPayload,
  UrlLinkPayload,
}                           from '../schemas/mod.js'

export type {
  ContactPayload            as Contact,
  EventDirtyPayload         as EventDirty,
  EventDongPayload          as EventDong,
  EventErrorPayload         as EventError,
  EventFriendshipPayload    as EventFriendship,
  EventHeartbeatPayload     as EventHeartbeat,
  EventLoginPayload         as EventLogin,
  EventLogoutPayload        as EventLogout,
  EventMessagePayload       as EventMessage,
  EventReadyPayload         as EventReady,
  EventResetPayload         as EventReset,
  EventRoomInvitePayload    as EventRoomInvite,
  EventRoomJoinPayload      as EventRoomJoin,
  EventRoomLeavePayload     as EventRoomLeave,
  EventRoomTopicPayload     as EventRoomTopic,
  EventScanPayload          as EventScan,
  FriendshipPayload         as Friendship,
  FriendshipPayloadConfirm  as FriendshipConfirm,
  FriendshipPayloadReceive  as FriendshipReceive,
  FriendshipPayloadVerify   as FriendshipVerify,
  LocationPayload           as Location,
  MessagePayload            as Message,
  MessagePayloadBase        as MessageBase,
  MessagePayloadRoom        as MessageRoom,
  MessagePayloadTo          as MessageTo,
  MiniProgramPayload        as MiniProgram,
  RoomInvitationPayload     as RoomInvitation,
  RoomMemberPayload         as RoomMember,
  RoomPayload               as Room,
  UrlLinkPayload            as UrlLink,
}
